apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: gateway
spec:
  hostnames:
    - argocd.home.fedoteh.com.ar
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: home-gw
      namespace: gateway
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: argocd-server
          namespace: argocd
          port: 80
          weight: 1
