apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oled-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fedoteh/k8s-on-raspberry-pi.git
    targetRevision: main
    path: apps/oled-agent/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
